# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 07:42
from __future__ import unicode_literals

import cms.stream_blocks
from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_section_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionpage',
            name='intro',
            field=wagtail.wagtailcore.fields.StreamField((('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('html', wagtail.wagtailcore.blocks.RawHTMLBlock()), ('page', wagtail.wagtailcore.blocks.PageChooserBlock()), ('blockquote', cms.stream_blocks.BlockQuoteBlock())), blank=True, null=True),
        ),
    ]
