# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formpage',
            name='subject',
            field=models.CharField(default='No subject', max_length=100),
        ),
    ]
