# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 08:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeheardLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('sender_name', models.CharField(blank=True, max_length=128)),
                ('sender_email', models.EmailField(default='', max_length=64)),
                ('sender_location', models.CharField(blank=True, max_length=128)),
                ('recip_name', models.CharField(blank=True, max_length=128)),
                ('recip_email', models.EmailField(default='', max_length=64)),
                ('recip_bioguide_id', models.CharField(blank=True, max_length=12)),
                ('cust_msg', models.TextField(blank=True, help_text='Custom message entered by user')),
            ],
        ),
    ]
